index.js
package.json

npm3 uses dedup and word-warp is not in the node_modules dir from __dirname

fix(): fix for npm3

---

README.md
index.js
spec/czCustomizableSpec.js

Also fixes the issue with question mark in the next line
BREAKING CHANGE:
users now dont need to manually type the words CLOSED ISSUES
This tool will automatically add for you.
ISSUES CLOSED: #22 and #24

feat: add work CLOSED ISSUES automatically

---

README.md
index.js

now users can specify any location and name for the configuration file. This is done in your
package.json. Please refer to latest readme.md file for further details
ISSUES CLOSED: #26

feat: add option to specify config file via package.json

---

README.md
buildCommit.js
index.js
package.json
questions.js
spec/czCustomizableSpec.js
spec/questionsSpec.js

BREAKING CHANGE:
you need to update commitizen to v2.8.1, which uses inquireJs v1.0.2. From now on commitizen uses
promise for the commit callback. As a user of this adapter, all you have to do is update commitizen.
ISSUES CLOSED: 30

fix: update this module to work with latest commitizen v2.8.1

---

README.md

The GitHub markdown rendered what was supposed to be three lines, into a single line.
The new code block with three back ticks fixes this.

docs: Fix markdown example output issue

---

README.md
index.js
package.json

feat: add inquirer as dependency
Upgraded commitizen to the latest.
BREAKING CHANGE:
please reinstall the latest 2.9.5 commitizen globally via npm -i commitizen. Deprecated
configuration option has been removed.
ISSUES CLOSED: #34

feat: add inquirer as dependency

---

README.md
cz-config-EXAMPLE.js
index.js
questions.js

For my use case (a [lerna](https://www.npmjs.com/package/lerna) based monorepo) quite often I could be committing inside a package with a `package.json`. Which wouldn't have the `cz-customizable` config in. So I've added the ability to use a predefined name for the config file, resolved using `find-config` and added message overrides.

improve config discovery with defaults and allow message overides

---

README.md
buildCommit.js
index.js
questions.js
spec/czCustomizableSpec.js

Add config options for commit message block prefixes. Set ‘BREAKING CHANGE:’ and ‘ISSUES CLOSED:’ as the default.

feat(config): configurable commit block prefixes

---

cz-config-EXAMPLE.js
index.js
questions.js
spec/questionsSpec.js

I think it's better to remind user when their subject message exceed limit and  let them rewrite their subject.

feat: able to customize length limit of subject and warn when exceed

---

index.js

Attempting to `edit` a commit message via the prompt on Node v8 you'll get a depreaction warning: `(node:22043) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.` In Node v10, this will throw an error ([Deprecation Doc: DEP0013](https://nodejs.org/api/deprecations.html#deprecations_dep0013_fs_asynchronous_function_without_callback)).
This PR removes deprecated call and thus adds Node v10 support.
This addresses: https://github.com/leonardoanalista/cz-customizable/issues/14#issuecomment-366460703

feat: add Node v10 support

---

index.d.ts
package.json

ISSUES CLOSED: #57 
You can now write your config file in Typescript with type safety. Just import the type as normal: 
`import { Options } from "cz-customizable";`

feat: add Typescript type definition file

---

buildCommit.js
cz-config-EXAMPLE.js
questions.js
spec/czCustomizableSpec.js
spec/questionsSpec.js

now users can configure a ticket-number question before the subject
ISSUES CLOSED: #50

feat: add ticket-number question

---

README.md
index.js

Allow and document a second config option:
* as it is today
Standalne - No Changes to your git repository*. This is suitable when your team is not ready to roll `cz-customizable` across all teams but you still would like to use it for your own commits, no matter the project.
Steps:
* create config file:
* create a file called `.cz-config.js` in your git repository root (*Asumptions: you do a global git ignore on `~/.gitignore_global` for `.cz-config.js`). Or;
* create a file called `.cz-config.js` your home directory.
* npm install -g commitizen
* npm install -g cz-customizable. Make sure you have version `>v5.6.x`
* create global commitizen config file `.czrc`: `echo '{ "path": "cz-customizable" }' > ~/.czrc`
* now run: `npx git-cz` or `git cz`.

feat: make entry point executable

---

README.md
buildCommit.js
package-lock.json
package.json
spec/buildCommitSpec.js

* feat: add options `subjectSeparator`, `typePrefix` and `typeSuffix`
This will allow a lot more flexibility to construct any kind of commit message pattern. Examples:
* `feat(myScope): create a new cool feature`
* `feat(myScope) - create a new cool feature`
* `feat - create a new cool feature`
* `[feat] create a new cool feature`
* Added `lodash` dependency. We can now make use of `lodash` in any new code!

feat: add options subjectSeparator typePrefix and typeSuffix

---

README.md
buildCommit.js
spec/czCustomizableSpec.js

Respect configuration's `{ footerPrefix: '' }` which will produce
```
...commit
${whateverThereIsForFooter}
```
Instead setting default `ISSUES CLOSED`

feat: add possibility to set empty footerPrefix

---

README.md
buildCommit.js
cz-config-EXAMPLE.js
index.js
questions.js
spec/buildCommitSpec.js

feat: add option for breakline in footer and body
* new config options has been added: `breaklineChar, default is '|``.
* `breakline` is supported by fields `body` and now `footer`
ISSUES CLOSED: #29

feat: add option for breakline in footer and body

---

README.md
questions.js
spec/questionsSpec.js

Adds `{ upperCaseSubject }` (default `false`) to configuration.
This follows the pattern:
| upperCaseSubject | Input Subject | Output Subject |
|:------------------:|:--------------:|:---------------:|
| `true`                     | `some subject`| `Some subject`|
| `false` (default)    | `Some subject`| `some subject`|

feat: add configuration option upperCaseSubject

---

questions.js

We would like to use cz-customizable in our company and we think it makes sense to be able to press ENTER until the end, without any extra effort, until you've created the commit. Hence, we propose to make 'yes' the default option in confirmCommit

fix: `yes` should be default for confirmCommit

---

.eslintrc
.travis.yml
README.md
cz-config-EXAMPLE.js
package-lock.json
package.json
standalone.js

feat: standalone version of this lib
This will allow to run this lib without installing commitizen.
Run as npm script (`package.json`):
```
"scripts" : {
"build": "your build script"
"commit": "./node_modules/cz-customizable/standalone.js"
}
```
ISSUES CLOSED: #89

feat: standalone version of this lib

---

README.md
buildCommit.js
index.js
spec/czCustomizableSpec.js
spec/questionsSpec.js

Current changes solve next problems:
1. subjectLimit property overrides by defaultMaxLineWidth.
2. Subject message validates by subjectLimit property, but when it trims, include prefix and scope – trim does not correct.

subjectLimit option usage and validation

---

README.md

A lot of people prefer using a `.config` folder to limit the number of files at the root of their repository.
Good news! *cz-customizable* uses [find-config](https://www.npmjs.com/package/find-config) which looks up for both `.cz-config.js` and `.config/cz-config.js`.
This PR is to mention it in the docs!

docs: mention possible alternative path for config

---

questions.js
spec/questionsSpec.js

There are two kind of people:
- Those who `git commit`
- Those who `git commit -m`
*cz-customizable* is for those who `git commit`
With this PR, *cz-customizable* is now for everybody!
When used as a git hook, using `git commit -m'my message'` was not making use of `'my message'`. **Now it does.**
This PR adds support for
- **single line** commit messages. The message is passed as the default answer for the `subject` question
- **multi line** commit messages. The first line is passed as the default answer for the `subject`question and the other lines are passed as the default answer for the `body` question
It is non invasive as it is passed as a `default` to enquirer. So the user can just press enter to use it or type another message if he wishes to.

fix: support prepared commit message

---

package.json

I forgot to update the package url with the new organization name

fix: package url inside package.json after org creation

---

README.md

'bellow' should be 'below'
bellow - verb -  (of a person or animal) emit a deep loud roar, typically in pain or anger.
below - preposition - at a lower level or layer than.

docs: minor typo in read me

---

README.md
questions.js

This adds a simple boolean to the config, so that the question for scopes can be skipped if no scopes are defined. This is useful for example if you use scope overrides to add scopes only to a subset of types.

feat: Allow to skip scope question

---

README.md
__tests__/cz-customizable.test.js
cz-config-EXAMPLE.js
jest.config.js
lib/questions.js
lib/utils/get-previous-commit.js
package-lock.json
package.json

fix: add option usePreparedCommit default false
**TODO: it needs unit tests for coverage**
ISSUES CLOSED: #173

fix: add option usePreparedCommit default false

---

lib/build-commit.js

Add breaklines before wrap body
For example:
```
* foobar foobar foobar foobar foobar foobar foobar foobar foobar foobar foobar foobar foobar|* foobar foobar foobar foobar foobar foobar foobar foobar foobar foobar foobar foobar foobar 
```
Wrap first, split line at 100 characters
```
* foobar foobar foobar foobar foobar foobar foobar foobar foobar foobar foobar foobar foobar|* 
foobar foobar foobar foobar foobar foobar foobar foobar foobar foobar foobar foobar foobar 
```
Then split with "|":
```
* foobar foobar foobar foobar foobar foobar foobar foobar foobar foobar foobar foobar foobar
* 
foobar foobar foobar foobar foobar foobar foobar foobar foobar foobar foobar foobar foobar 
```
The output is correct:
```
* foobar foobar foobar foobar foobar foobar foobar foobar foobar foobar foobar …
```

fix: incorrect body split

---

README.md
lib/build-commit.js
lib/questions.js

You can add n number of additional questions for commit.
And append  answers to the body of commit message.
These question can help you to create smart-commit and pass information to third party like jira (with help of mapping)

feat(additionalQuestion): support additional questions for commit
